type StatsDataPoint {
  revenueCents: Int!
  numParkingSessions: Int!
}

type YearStats {
  year: PositiveInt!
  data: StatsDataPoint!

  # Max length is 4.
  # quarterly: [QuerterStats!]
  # Max length is 12.
  monthly: [MonthStats!]
}

# type QuerterStats {
#   quarter: PositiveInt!
#   data: StatsDataPoint!

#   monthly: [MonthStats!]!
# }

type MonthStats {
  year: PositiveInt!
  month: PositiveInt!

  data: StatsDataPoint!
  daily: [DayStats!]!
}

type DayStats {
  year: PositiveInt!
  month: PositiveInt!
  date: PositiveInt!

  data: StatsDataPoint!
  hourly: [HourStats!]!
}

type HourStats {
  hour: String!
  data: StatsDataPoint!
}

extend type Query {
  yearStats(year: PositiveInt!): YearStats!
  monthStats(year: PositiveInt!, month: PositiveInt!): MonthStats!
  dayStats(
    year: PositiveInt!
    month: PositiveInt!
    date: PositiveInt!
  ): DayStats!
  dayStatsAll: MonthStats!
}
