image: node:12.13.0

cache:
  paths:
    - node_modules/

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - test
  - build

# STAGES #

test:
  stage: test
  script:
    - npm install --silent
    - npm run compile
    - npm run test:ci

build:
  image: docker:19.03.8
  stage: build
  only:
    - master
  services:
    - docker:19.03.8-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
