type Device {
  name: String!
  activated: Boolean!
  activatedAt: DateTime
  activationPassword: Authentication!
  # Calculated
  activationQrUrl: String!
}

extend type Query {
  devices: [Device]!
  activatedDevices: [Device]!
  notActivatedDevices: [Device]!
}

input NewDeviceInput {
  name: String!
}

extend type Mutation {
  addDevice(input: NewDeviceInput!): Device
}
