type Device {
  id: ID
  name: String!
  activated: Boolean!
  activatedAt: DateTime
  activationPassword: Authentication!
  # Calculated
  activationQrUrl: String!
}


input NewDeviceInput {
  name: String!
}

input DeviceFilter {
  id: ID
  name: String
  activated: Boolean
  activatedAt: DateTime
}

extend type Query {
  devices(filter: DeviceFilter): [Device]!
}

extend type Mutation {
  addDevice(input: NewDeviceInput!): Device!
}
