type User {
  _id: ID!
  name: String!
  email: String!
  permissions: [String!]!
  authentications: [Authentication]
  refreshTokens: [RefreshToken]
}

extend type Query {
  currentUser: User
  users: [User!]!
}
