type User {
  _id: ID!
  name: String!
  email: EmailAddress!
  permissions: [String]!
  authentications: [Authentication]
  refreshTokens: [RefreshToken]
}

extend type Query {
  currentUser: User
  users: [User!]!
}
