type User {
  id: ID!
  name: String!
  email: EmailAddress!
  permissions: [Permission]!
  authentications: [Authentication]
  refreshTokens: [RefreshToken]
  isAdmin: Boolean!
  active: Boolean!
}

input UserSearchInput {
  name: String!
  limit: PositiveInt
  page: PositiveInt
}

input UserByEmailSearchInput {
  email: String!
  limit: PositiveInt
  page: PositiveInt
}

input UserUpdateInput {
  permissions: [Permission!]
  active: Boolean
  name: String
}

type UserSearchResult {
  data: [User!]
  page: PositiveInt!
  limit: PositiveInt!
}

extend type Query {
  currentUser: User!
  userSearch(search: UserSearchInput!): UserSearchResult!
  userSearchByEmail(search: UserByEmailSearchInput!): UserSearchResult!
}

extend type Mutation {
  updateUser(id: ID!, input: UserUpdateInput!): User!
}
