enum AuthenticationMethod {
  PASSWORD
  ACTIVATION_PASSWORD
}

type Authentication {
  method: AuthenticationMethod!
}

type LoginResult {
  refreshToken: String!
  accessToken: String!
  user: User!
}

input PasswordChangeInput {
  newPassword: String!
  # Admin can change someone else's password. Normal users have to provide their current password.
  currentPassword: String
  # Admin can change someone else's password.
  user: ID!
}

extend type Mutation {
  passwordLogin(user: String!, password: String!): LoginResult!
  # Requires a valid access token
  passwordChange(input: PasswordChangeInput!): String!
}
