enum AuthenticationMethod {
  PASSWORD
  ACTIVATION_PASSWORD
}

type Authentication {
  method: AuthenticationMethod!
}

type LoginResult {
  refreshToken: String!
  accessToken: String!
  user: User!
}

extend type Mutation {
  passwordLogin(user: String!, password: String!): LoginResult!
}
